services:
  neo4j:
    image: neo4j:5-community
    container_name: banking_bot_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file: .env
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs:
